### ISSUE TITLE
Make low fidelity sketches

### ISSUE THREAD

**Issue by Inioluwa21** [relatable-course-visualization/Relatable#13]
You can use the 10+10 design method talked about in CMPT 381 (due Tuesday 1:00pm)

![image](https://user-images.githubusercontent.com/83588481/222928983-607e6b01-f125-4871-9431-267b256b9378.png)

**Comment by marmikpatel19** [comment]
Feel free to create a subdirectory called "design" on the main repo folder and place the final designs there
