### ISSUE TITLE
Develop about us page

### ISSUE THREAD

**Issue by marmikpatel19** [relatable-course-visualization/Relatable#21]
This should be based on the about us page design

**Comment by marmikpatel19** [comment]
Needs to be redone using MUI. Small UI fixes necessary as noted in a previous meeting doc. Newly assigned to @kyle-boughen 5/28/2023

**Comment by fraser-mcleod** [comment]
Self notes:
- add text and change font weight, size, and family
- leave the ticket open after fixes are made, but still merge branch to main

**Comment by fraser-mcleod** [comment]
Create a relatable email and add contact information

**Comment by fraser-mcleod** [comment]
Also add link to GitHub repo
