### ISSUE TITLE
Restructure Course Table

### ISSUE THREAD

**Issue by marmikpatel19** [relatable-course-visualization/Relatable#31]
Reference the discussion had here: [meeting](https://usaskca1-my.sharepoint.com/:w:/r/personal/qay871_usask_ca/_layouts/15/Doc.aspx?sourcedoc=%7BD9F07B11-CE34-4AD4-9BB4-23BF50662BEA%7D&file=Prequisite%20Storage%20Planning%20(3.31.2023).docx&action=default&mobileredirect=true)

**Comment by fraser-mcleod** [comment]
Self note of things to complete in this branch:
1. Clean up models.py, views.py, urls.py, serializers.py, and webscraping folder to remove/comment out old unused code
2. Create new db table 'CourseTable2023' with additions as proposed in meeting
