### ISSUE TITLE
Complete_DB_Functions

### ISSUE THREAD

**Issue by fraser-mcleod** [relatable-course-visualization/Relatable#34]
Need to create the following functions and post/put functions:
1. Clean_Preq
2. Marked_Preq
3. Dependencies

It will likely be helpful (and necessary) to create helper get function from DB.

**Comment by fraser-mcleod** [comment]
I will create helper get function and then work on clean_preq, then leave the rest to you Marmik? @marmikpatel19

**Comment by marmikpatel19** [comment]
Sure, I think we said that I can take care of the function that converts the strings to the client-side-friendly format. Is that what you're taking about? @fraser-mcleod
