### ISSUE TITLE
Courses not in Catalogue

### ISSUE THREAD

**Issue by fraser-mcleod** [relatable-course-visualization/Relatable#38]
As we discussed on Wednesday, some preq strings reference courses that are no longer offered at USask. We would like to add these courses into DB, however, they must have a clear flag. The file 'postDependentCourses.py' has a notInCatalogue list
 which stores all course codes that do not have a matching row entry in the db (and therefore are not in the course catalogue). We would like to add these to the db and create a flag for them. Create the flag as you see fit, however, if you add another column (which you likely will need to), you will have to edit models and all other post/put functions. Big picture:

1. Decide how to flag courses and make this update in all the affected files
2. In post dependency, post all courses not in catalogue to DB with the flag

**Comment by marmikpatel19** [comment]
not_in_catalogue is not included in courseClass.py as it is not a part of the scrape and the default value is False
