### ISSUE TITLE
special course card for non-catalogue courses

### ISSUE THREAD

**Issue by marmikpatel19** [relatable-course-visualization/Relatable#43]
In #38, courses not in the catalogue were added to the CourseTable2023 table using a new column not_in_catalogue. 0 indicates that the course exists; 1 indicates that it does not. 

The course card component should include conditional rendering to render a `course not in catalogue` UI if the given course is not in the catalogue. 

The logic for this from the endpoint should be complete from #36 . This issue simply focuses on creating the conditional UI render. 

Blocker: #36

**Comment by marmikpatel19** [comment]
I've done the conditional rendering already in #36. It simply needs the UI to be fixed. Currently, there's a bug where the course card  for a not_in_catalogue course flickers when hovered over.

**Comment by marmikpatel19** [comment]
Example courses to use for testing and reference: plsc 314, acb 330, biol 107

**Comment by fraser-mcleod** [comment]
We should add a back button/function if you go to a course that is no longer in the catalogue. Especially if you reach it through a prerequisite.
