### ISSUE TITLE
update course button UI

### ISSUE THREAD

**Issue by marmikpatel19** [relatable-course-visualization/Relatable#47]
Current the buttons rendered for prerequisites and dependencies are the default MUI buttons.

Improve the UI so that they
- Aren't too large like they are right now
- Match Relatable color scheme
- Look less like traditional buttons

Screenshots:
![image](https://github.com/relatable-course-visualization/Relatable/assets/90867690/2998131d-1932-421c-9e69-7060483dc479)

Blockers: #36

**Comment by fraser-mcleod** [comment]
Hahahaha you are a step ahead of me! Exact comments I left on issue 36

**Comment by Inioluwa21** [comment]
Moved to Marmik.
