### ISSUE TITLE
footer covers show more button

### ISSUE THREAD

**Issue by marmikpatel19** [relatable-course-visualization/Relatable#49]
There is a "show more" button on the search component. The Search limits the number of shown courses to 10 and allows repeated display of 10 more every time the show more button is clicked. However, the footer seems to be hiding this button. 

### Screenshots
At the bottom of the page but the button is not visible.
![image](https://github.com/relatable-course-visualization/Relatable/assets/90867690/e1dcbdb4-4f16-4806-b826-8c560619ffc1)

**Comment by fraser-mcleod** [comment]
Pretty much the same issue on About Us page, the footer covers content instead of being placed after all content

**Comment by fraser-mcleod** [comment]
Blocker for ticket #42
